### ISSUE TITLE
Permission to port mod to 1.19.2

### ISSUE THREAD

**Issue by sigmastar00** [Technici4n/FastCaps#2]
Hi, after profiling a 1.19.2 server I noticed that a lot of time was being spent in the `areCapsCompatible` method. A google search led me to this mod, but I see its only available for 1.16. I wanted to take a look at this mod's code and see if any of it would be relevant for 1.19.2, however this repo doesn't have a license file inside it. Hence, I'd like to ask permission to work with this mod's code before I mess around with it.

**Comment by Technici4n** [comment]
Yes do whatever with the code.
